apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo-dev
nameSuffix: -dev
commonLabels:
  variant: dev

resources:
  - namespace.yaml
  - ../base

images:
  - name: cartservice
    newName: registry.digitalocean.com/microservices-demo/cartservice
    newTag: 1.0.0-dev
  - name: checkoutservice
    newName: registry.digitalocean.com/microservices-demo/checkoutservice
    newTag: 1.0.0-dev
  - name: currencyservice
    newName: registry.digitalocean.com/microservices-demo/currencyservice
    newTag: 1.0.0-dev
  - name: emailservice
    newName: registry.digitalocean.com/microservices-demo/emailservice
    newTag: 1.0.0-dev
  - name: frontend
    newName: registry.digitalocean.com/microservices-demo/frontend
    newTag: 1.0.0-dev
  - name: paymentservice
    newName: registry.digitalocean.com/microservices-demo/paymentservice
    newTag: 1.0.0-dev
  - name: productcatalogservice
    newName: registry.digitalocean.com/microservices-demo/productcatalogservice
    newTag: 1.0.0-dev
  - name: recommendationservice
    newName: registry.digitalocean.com/microservices-demo/recommendationservice
    newTag: 1.0.0-dev
  - name: shippingservice
    newName: registry.digitalocean.com/microservices-demo/shippingservice
    newTag: 1.0.0-dev

secretGenerator:
  - name: digitalocean-dns
    env: configs/do/pat.env
