name: Online Boutique PR Kustomize Validation

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "kustomize/**"

env:
  KUBECONFORM_VERSION: "0.5.0"
  KUBERNETES_VERSION: "1.24.4"

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconform
        run: |
          (
            cd /tmp
            wget "https://github.com/yannh/kubeconform/releases/download/v${{ env.KUBECONFORM_VERSION }}/kubeconform-linux-amd64.tar.gz"
            tar xvf kubeconform-linux-amd64.tar.gz
            chmod u+x ./kubeconform
          )

      - name: Kustomize linting using kubeconform
        run: |
          # Test each overlay using kubeconform
          for kustomize_overlay in kustomize/*/; do
            kustomize build "$kustomize_overlay" | \
              /tmp/kubeconform -kubernetes-version "${{env.KUBERNETES_VERSION}}" -summary -verbose
          done
